### ISSUE TITLE
Should this package be included in the Tracking CTV?

### ISSUE THREAD

**Issue by rociojoo** [samhforbes/eyetrackingR#1]
Hi @samhforbes . I'm co-maintaining the [Tracking CTV](https://cran.r-project.org/web/views/Tracking.html) and I am wondering if your package would be a good fit. Could you please follow [this issue](https://github.com/cran-task-views/Tracking/issues/12#issue-1250244277) and reply there if you're interested? 

Thank you,
Rocío

**Comment by samhforbes** [comment]
responded at the source
